/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin2' at '09.08.16 8:41' with Gradle 2.11
 *
 * @author admin2, @date 09.08.16 8:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
